### ISSUE TITLE
Javascript parsing error for my internal web app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arpithparikh/script-cover#4]
```
What steps will reproduce the problem?
1. Build the extension
2. Load a webapp
3. Try to run the extension

What is the expected output? What do you see instead?

Expected output is some kind of report. Instead I get a "please wait" bubble"

What version of the product are you using? On what operating system?

Chrome 15.0.874.102 on Mac OS X 10.6.8, script-cover version is 
67322113de23e4a3266f6475eab3af9a3713f68a (github repo)

Please provide any additional information below.

In the console I see the extension request a number of external scripts and 
then an error:

Error in event handler for 'undefined': TypeError: object is not a function
    at Object.CALL_NON_FUNCTION (native)
    at new JS_Parse_Error (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:234:20)
    at js_error (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:245:15)
    at croak (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:651:17)
    at token_error (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:658:17)
    at unexpected (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:664:17)
    at Object.semicolon [as 1] (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:684:51)
    at prog1 (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:1201:28)
    at simple_statement (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:815:35)
    at $statement (chrome-extension://opcmnmjgebbdnekdanmkioiibcfdemoc/third_party/lib/parse-js.js:725:35)
```

Original issue reported on code.google.com by `maciekad...@gmail.com` on 27 Oct 2011 at 7:26
- Merged into: #6

**Comment by GoogleCodeExporter** [comment]
```
Is there any chance to get a link to your application to inspect its Javascript?
It is going to be hard to fix this not looking into that page.
```

Original comment by `ekamensk...@google.com` on 27 Oct 2011 at 8:16
- Added labels: **FeedbackRequested**

**Comment by GoogleCodeExporter** [comment]
```
Hi, sorry it's an internal app for now. I'll keep trying to whittle it down to 
a test case.
```

Original comment by `maciekad...@gmail.com` on 27 Oct 2011 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
It seems that Javascript parsing (implemented by third-party library) is 
failing for a portion of Javascript. If you you provided Javascript code 
snippet which causes the error, then it would be easier to fix that. Let me 
know, if I can help.

```

Original comment by `ekamensk...@google.com` on 27 Oct 2011 at 8:36

**Comment by GoogleCodeExporter** [comment]
Original comment by `ekamensk...@google.com` on 27 Oct 2011 at 8:38
- Changed title: **Javascript parsing error for my internal web app**

**Comment by GoogleCodeExporter** [comment]
```
I merge this issue into issue #6, because there we have an URL and can start 
debugging.
```

Original comment by `ekamensk...@google.com` on 3 Nov 2011 at 9:15
- Changed state: **Duplicate**
- Added labels: **OpSys-All**
- Removed labels: **FeedbackRequested**
