### ISSUE TITLE
ScriptCover returns JS_Parse_Error at http://www.lastminute.com/

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arpithparikh/script-cover#6]
```
What steps will reproduce the problem?
1. Visit a page with script-cover installed
2. Click JS icon
3. Note popup: "Please wait..."
It doesnt go beyond this stage. I have tried 20 times I got the report only 
once. And I notice my web pages loading looks very slow now.

What is the expected output? What do you see instead?
Coverage Report should be shown

What version of the product are you using? On what operating system?
1.0.0.1

Please provide any additional information below.
My chrome version : 15.0.874.106 m
```

Original issue reported on code.google.com by `chida....@gmail.com` on 3 Nov 2011 at 8:31

**Comment by GoogleCodeExporter** [comment]
```
Please, mention which URL you visit (I need it to debug your case) or you see 
it for all pages, your operation system. 

```

Original comment by `ekamensk...@google.com` on 3 Nov 2011 at 8:40
- Added labels: **FeedbackRequested**

**Comment by GoogleCodeExporter** [comment]
```
http://www.lastminute.com/
or 
http://globaltrips.lastminute.com/trips/hotellist/listInternal?pTxId=1577177&sta
rtIndex=0&checkInDate=2011-11-03&checkOutDate=2011-11-04&hotelMaxReturnPerPage=2
5&guestCounts=2&guestCodes=ADULT&configId=S72722479&city=bangalore&numRooms=1&in
tcmp=home1_hotels&path=hotels

```

Original comment by `chida....@gmail.com` on 3 Nov 2011 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
and my operating system is Windows XP
```

Original comment by `chida....@gmail.com` on 3 Nov 2011 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
JS error when using ScriptCover at http://www.lastminute.com/:

Error in event handler for 'undefined': TypeError: object is not a function
    at Object.CALL_NON_FUNCTION (native)
    at new JS_Parse_Error (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:234:20)
    at js_error (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:245:15)
    at croak (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:651:17)
    at token_error (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:658:17)
    at unexpected (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:664:17)
    at Object.semicolon [as 1] (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:684:51)
    at prog1 (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:1201:28)
    at simple_statement (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:815:35)
    at $statement (chrome-extension://aganjnlggfbbkncijljbhbebpbglloop/third_party/lib/parse-js.js:725:35)
```

Original comment by `ekamensk...@google.com` on 3 Nov 2011 at 9:11
- Changed state: **Accepted**
- Added labels: **OpSys-All**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ekamensk...@google.com` on 3 Nov 2011 at 9:13
- Changed title: **ScriptCover returns JS_Parse_Error at http://www.lastminute.com/**
- Removed labels: **FeedbackRequested**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ekamensk...@google.com` on 3 Nov 2011 at 9:13

**Comment by GoogleCodeExporter** [comment]
```
Thanks 
```

Original comment by `chida....@gmail.com` on 3 Nov 2011 at 9:13

**Comment by GoogleCodeExporter** [comment]
```
Issue 4 has been merged into this issue.
```

Original comment by `ekamensk...@google.com` on 3 Nov 2011 at 9:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `ekamensk...@google.com` on 11 Nov 2011 at 11:44
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ekamensk...@google.com` on 24 Nov 2011 at 10:01
